name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Build BrightIntosh Local
        run: |
          xcodebuild \
            -project BrightIntosh.xcodeproj \
            -scheme BrightIntosh \
            -configuration Release \
            -derivedDataPath build \
            -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build
